spec:
  template:
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: ldap
        - name: LDAP_USER
          valueFrom:
            secretKeyRef:
              name: ldap-secrets
              key: ldap.user
        - name: LDAP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ldap-secrets
              key: ldap.password

