server:
  port: 8080
  ssl:
    enabled: false
    key-store: classpath:security/keystore.jks
    key-alias: digicert_aliaspaytest.servicii.transfond.ro
    key-password: changeit
    trust-store: classpath:security/truststore.jks
    trust-store-password: changeit
    client-auth: want
 
commonprops:
  message: HelloInt
 
logging:
  level:
    org:
      springframework:
        web: TRACE
        

